
deployUrl=file:///Users/cer/.m2/testdeploy
dockerComposePluginVersion=0.17.7

eventuateMavenRepoUrl=file:///Users/cer/.m2/testdeploy,https://snapshots.repositories.eventuate.io/repository

kafkaClientVersion=3.1.1

springBootVersion=4.1.1
slf4jVersion=2.0.18
micronautVersion=2.4.1

eventuateUtilVersion=0.20.0.BUILD-SNAPSHOT
eventuateCommonMessagingVersion=0.18.0.BUILD-SNAPSHOT

eventuatePluginsGradleVersion=0.15.0.BUILD-SNAPSHOT
junitVersion=6.0.3
junitPlatformLauncherVersion=6.0.3
eventuateCommonImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateCommonVersion=0.22.0.BUILD-SNAPSHOT
assertjVersion=3.27.7
testContainersVersion=2.0.5
mockitoVersion=5.23.0
hamcrestVersion=3.0
commonsLang3Version=3.20.0
sbeVersion=1.32.1
jetbrainsAnnotationsVersion=17.0.0

version=0.22.0-SNAPSHOT
