
dependencies {

    api project (':eventuate-messaging-kafka-common')
    api project (':eventuate-messaging-kafka-consumer')
    api project (':eventuate-messaging-kafka-producer')
    api "io.eventuate.util:eventuate-util-test:$eventuateUtilVersion"

    implementation  project (":eventuate-messaging-kafka-basic-consumer")
    implementation "io.eventuate.common.messaging:eventuate-messaging-partition-management:$eventuateCommonMessagingVersion"
    implementation "org.junit.jupiter:junit-jupiter:$junitVersion"

    implementation "org.apache.kafka:kafka-clients:$kafkaClientVersion"
    implementation "org.mockito:mockito-core:$mockitoVersion"
    implementation "org.assertj:assertj-core:$assertjVersion"



}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
