#! /bin/bash -e

set -e

EFFECTIVE_KAFKA_CONFIG_DIR=./config

cp -v /usr/local/kafka-config/* $EFFECTIVE_KAFKA_CONFIG_DIR

sed -i \
 -e "s?KAFKA_LISTENERS?${KAFKA_LISTENERS?}?"  \
 -e "s?KAFKA_ADVERTISED_LISTENERS?${KAFKA_ADVERTISED_LISTENERS?}?"  \
 -e "s?KAFKA_INTER_BROKER_LISTENER_NAME?${KAFKA_INTER_BROKER_LISTENER_NAME?}?"  \
 -e "s?KAFKA_ZOOKEEPER_CONNECT?${KAFKA_ZOOKEEPER_CONNECT?}?" \
 -e "s?KAFKA_LISTENER_SECURITY_PROTOCOL_MAP?${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP?}?" \
 -e "s?KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR?${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR?}?" \
  $EFFECTIVE_KAFKA_CONFIG_DIR/server.properties


exec bin/kafka-server-start.sh $EFFECTIVE_KAFKA_CONFIG_DIR/server.properties
