apply plugin: SbeToolPlugin

dependencies {
    implementation "org.apache.commons:commons-lang3:$commonsLang3Version"
    api "org.apache.kafka:kafka-clients:$kafkaClientVersion"

    implementation "uk.co.real-logic:sbe-all:$sbeVersion"

    implementation "org.slf4j:slf4j-api:$slf4jVersion"

    testImplementation "org.hamcrest:hamcrest:$hamcrestVersion"
}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
