name: Build, and test

on:
  push:

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        java-package: jdk
        distribution: corretto

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false

    - name: Build
      run: ./gradlew :eventuate-messaging-kafka-testcontainers:clean :eventuate-messaging-kafka-testcontainers:test --tests "io.eventuate.messaging.kafka.testcontainers.EventuateKafkaNativeClusterTest"


    - name: Save test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          **/build/reports
          **/build/test-results

    - name: get container logs
      run: ./.github/workflows/print-container-logs.sh
      if: ${{ always() }}

    - name: Save container logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: container-logs
        path: ~/container-logs

    - name: Save test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          **/build/reports
          **/build/test-results
